version: 2.0
jobs:
  test:
    docker:
      - image: nhyox/codechan
    steps:
      - checkout
      - run: 
          name: test_pyhton
          command: 
            python tests.py
      - store_test_results:
          path: .
      - persist_to:workspace:
          root: .
          paths:
            - .
