version: 2.0
jobs:
  build:
    docker:
      - image: python
    steps:
      - checkout
      - run: 
          name: test_pyhton
          command: |
            pip install -r requirments.txt /ca-project/
            python tests.py
      - store_test_results:
          path: .
