version: 2.0
jobs:
  test:
    docker:
      - image: nhyox/codechan
    steps:
      - checkout
      - run: 
          name: test_pyhton
          command: 
            python tests.py
      - store_test_results:
          path: .
      - persist_to_workspace:
          root: .
          paths:
            - .
  package:
    machine: true
    steps:
      - attach_workspace:
          at: . 
      - run:
          name: package
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker build -t nhyox/codechan:$CIRCLE_SHA1 .
            docker push nhyox/codechan:$CIRCLE_SHA1
  deploy:
    machine: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "bc:b2:8d:c5:3c:61:9e:44:93:37:a3:2b:cf:36:09:a2"
      - run:
          name: deploy with SSH
          command: |
            ssh ubuntu@146.148.18.14 "docker pull nhyox/codechan; docker container run -d nhyox/codechan"
            ssh ubuntu@35.233.29.74 "docker pull nhyox/codechan; docker container run -d nhyox/codechan"
workflows:
  version: 2 
  workflowstart:
    jobs:
      - test
      - package:
          requires:
            - test
      - deploy:
          requires:
            - package
